apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api
  labels:
    app: products-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products-api
  template:
    metadata:
      labels:
        app: products-api
    spec:
      containers:
      - name: products-api
        image: darin04/products-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_password
        - name: DB_URL
          value: "jdbc:mysql://products-db-instance-1.c32kue2earbr.ap-south-1.rds.amazonaws.com:3306/vinodses_ecomm"
---
apiVersion: v1
kind: Service
metadata:
  name: products-api-service
spec:
  type: LoadBalancer
  selector:
    app: products-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
